# QuantumPen by GamerCoder215
#
# Version v1.0.0
#
# Information for each option is in the comment ABOVE

# Disabled Commands
#
# Disabled Commands will return the usage arguments but will not do any actions.
# For listing, use the command name (case insensitive) without the "/"
# For example:
#
# DisabledCommands:
#  - createworld
#  - deleteworld
#
DisabledCommands:
  -
  
# UseTabComplete
# Enable the usage of suggestions with commands
UseTabComplete: true

# CalculateDigits
# The number of digits to display when large numbers are in scientific notation & decimal places
# Default: 7
CalculateDigits: 7