name: NovaEditor
main: me.gamercoder215.novaeditor.Main
version: 1.0.0
api-version: 1.17
description: Send NMS Packets with simple commands!
author: GamerCoder215
commands:
  clientpacket:
    description: Use a client-bound packet to a player.
    permission: novaeditor.packets.clientpacket
    usage: /clientpacket <player> <type> <packet> <parameters...>
    aliases: [cpacket, clientp, clpacket, clp, cp]
  novaeditor:
    description: NovaEditor base command
    usage: /novaeditor <parameters>
    aliases: [novae, ne, novaedit, nedit, neditor]
  pathfinders:
    description: Pathfinders base command
    usage: /pathfinders <add|remove|clear|list> <parameters>
    aliases: [pathfinder, pfinder, pf, pfs, pfinders, pathf, pathfs]

permissions:
  novaeditor.*:
    default: op
    description: All NovaEditor permissions
    children:
      novaeditor.packets: true
      novaeditor.packets.clientpacket: true
      novaeditor.pathfinder: true
      novaeditor.pathfinder.add: true
      novaeditor.pathfinder.remove: true
      novaeditor.pathfinder.clear: true
      novaeditor.pathfinder.list: true
  # Packets
  novaeditor.packets:
    default: op
    description: Access to NovaEditor packets
    children:
      novaeditor.packets.clientpacket: true
  novaeditor.packets.clientpacket:
    default: op
    description: Access to /clientpacket command
  # Pathfinders
  novaeditor.pathfinder:
    default: op
    description: Access to all Pathfinder Options
    children:
      novaeditor.pathfinder.add: true
      novaeditor.pathfinder.remove: true
      novaeditor.pathfinder.clear: true
      novaeditor.pathfinder.list: true
      
  