name: NovaEditor
main: me.gamercoder215.quantumpen.Main
version: 1.0.0
api-version: 1.17
description: Edit your world in previous ways unknown!
author: GamerCoder215
commands:
  clientpacket:
    description: Use a client-bound packet to a player.
    permission: quantumpen.packets.clientpacket
    usage: /clientpacket <player> <type> <packet> <parameters...>
    aliases: [cpacket, clientp, clpacket, clp, cp]
  quantumpen:
    description: NovaEditor base command
    usage: /quantumpen <parameters>
    aliases: [qpen, quantump, quantp, qp, quantpen]
  pathfinders:
    description: Pathfinders base command
    usage: /pathfinders <add|remove|clear|list> <parameters>
    aliases: [pathfinder, pfinder, pf, pfs, pfinders, pathf, pathfs]

permissions:
  quantumpen.*:
    default: op
    description: All NovaEditor permissions
    children:
      quantumpen.packets: true
      quantumpen.packets.clientpacket: true
      quantumpen.pathfinder: true
      quantumpen.pathfinder.add: true
      quantumpen.pathfinder.remove: true
      quantumpen.pathfinder.clear: true
      quantumpen.pathfinder.list: true
  # Packets
  quantumpen.packets:
    default: op
    description: Access to QuantumPen packets
    children:
      quantumpen.packets.clientpacket: true
  quantumpen.packets.clientpacket:
    default: op
    description: Access to /clientpacket command
  # Pathfinders
  quantumpen.pathfinder:
    default: op
    description: Access to all Pathfinder Options
    children:
      quantumpen.pathfinder.add: true
      quantumpen.pathfinder.remove: true
      quantumpen.pathfinder.clear: true
      quantumpen.pathfinder.list: true
  quantumpen.pathfinder.add:
    default: op
    description: Enable ability to add pathfinders
  quantumpen.pathfinder.list:
    default: op
    description: Enable ability to list pathfinders
  quantumpen.pathfinder.remove:
    default: op
    description: Enable ability to remove pathfinders
  quantumpen.pathfinder.clear:
    default: op
    description: Enable ability to clear pathfinders
    
      
  