name: NovaEditor
main: me.gamercoder215.novaeditor.Main
version: 1.0.0
api-version: 1.17
description: Send NMS Packets with simple commands!
author: GamerCoder215
commands:
  clientpacket:
    description: Use a client-bound packet to a player.
    permission: novaeditor.packets.clientpacket
    usage: /clientpacket <player> <type> <packet> <parameters...>
    aliases: [cpacket, clientp, clpacket, clp, cp]
  novaeditor:
    description: NovaEditor base command
    usage: /superpackets <parameters>
    aliases: [superp, spackets, superpacket, spacket, sp] 

permissions:
  novaeditor.*:
    default: op
    description: All NovaEditor permissions
    children:
      novaeditor.packets: true
      novaeditor.packets.clientpacket: true
  # Packets
  novaeditor.packets:
    default: op
    description: Access to NovaEditor packets
    children:
      novaeditor.packets.clientpacket: true
  novaeditor.packets.clientpacket:
    default: op
    description: Access to /clientpacket command
    children:
      novaeditor.packets.clientpacket: true
  #
  