name: NovaEditor
main: me.gamercoder215.novaeditor.Main
version: 1.0.0
api-version: 1.17
description: Send NMS Packets with simple commands!
author: GamerCoder215
commands:
  clientpacket:
    description: Use a client-bound packet to a player.
    permission: superpackets.clientpacket
    usage: /clientpacket <player> <type> <packet> <parameters...>
    aliases: [cpacket, clientp, clpacket, clp, cp]
  superpackets:
    description: SuperPackets base command
    usage: /superpackets <parameters>
    aliases: [superp, spackets, superpacket, spacket, sp] 

permissions:
  superpackets.*:
    default: op
    description: All SuperPacket permissions
    children:
      superpackets.clientpacket: true
      superpackets.superpackets: true
  superpackets.superpackets:
    default: op
    description: Allows /superpackets command
  superpackets.clientpacket:
    default: op
    description: Allows /clientpacket command