name: QuantumPen-Lite
main: me.gamercoder215.quantumpen.Main
version: 1.0.0
api-version: 1.17
description: Edit your world in previous ways unknown!
author: GamerCoder215
commands:
  clientpacket:
    description: Use a client-bound packet to a player.
    permission: quantumpen.packets.clientpacket
    usage: /clientpacket <type> <player> <packet> <parameters...>
    aliases: [cpacket, clientp, clpacket, clp, cp]
  quantumpen:
    description: NovaEditor base command
    usage: /quantumpen <parameters>
    aliases: [qpen, quantump, quantp, qp, quantpen]
  pathfinders:
    description: Pathfinders base command
    usage: /pathfinders <add|add_target|controller|remove_target|remove|clear|list> <player> <parameters...>
    aliases: [pathfinder, pfinder, pf, pfs, pfinders, pathf, pathfs]
  editentity:
    permission: quantumpen.world.entity
    description: Edit entities (advanced /data command)
    usage: /editentity <parameters...>
    aliases: [edite, eentity, ee, eden, edentity]
  block:
    permission: quantumpen.world.block
    description: Edit & Fetch data of blocks (World based on current world)
    usage: /block <world> <x> <y> <z> <parameters...>
    aliases: [bl, blck]
  createworld:
    permission: quantumpen.world.create
    description: Create a world or load an existing world
    usage: /createworld <name> <type> <options>
    aliases: [cworld, createw, cw]
  unloadworld:
    permission: quantumpen.world.unload
    description: Unload an existing world
    usage: /unloadworld <name>
    aliases: [uworld, uw, unloadw]
  chunk:
    permission: quantumpen.world.chunk
    description: Edit chunk data
    usage: /chunk <world> <x> <z> <load|unload|forceload|unforceload|setage|addticket|removeticket> <parameters...>
    aliases: [chnk, chk]
  world:
    description: Edit world data
    permission: quantumpen.world
    usage: /world <name> <action> <parameters...>
    aliases: [wrld, w]
  playerdata:
    description: Fetch & Modify player data
    permission: quantumpen.server.playerdata
    usage: /playerdata <player> <property|action>
    aliases: [pdata, playerd, pd, pdta]
  server:
    description: Edit & Fetch server data
    permission: quantumpen.server
    usage: /server <get|reloaddata|reloadwhitelist> <parameters...>
    aliases: [srvr, s]
  pen:
    description: Miscellaneous QuantumPen actions
    permission: quantumpen.misc
    usage: /pen <action> <parameters...>
    aliases: [miscellaneous, msc]

permissions:
  quantumpen.*:
    default: op
    description: All QuantumPen permissions
    children:
      quantumpen.misc: true
      quantumpen.packets: true
      quantumpen.packets.clientpacket: true
      quantumpen.pathfinder: true
      quantumpen.pathfinder.add: true
      quantumpen.pathfinder.remove: true
      quantumpen.pathfinder.clear: true
      quantumpen.pathfinder.list: true
      quantumpen.pathfinder.controller: true
      quantumpen.world: true
      quantumpen.world.block: true
      quantumpen.world.chunk: true
      quantumpen.world.create: true
      quantumpen.world.entity: true
      quantumpen.world.unload: true
      quantumpen.server.playerdata: true
      quantumpen.server: true
  quantumpen.misc:
    default: true
    description: Non-Admin Miscellaneous Actions
  # Packets
  quantumpen.packets:
    default: op
    description: Access to QuantumPen packets
    children:
      quantumpen.packets.clientpacket: true
  quantumpen.packets.clientpacket:
    default: op
    description: Access to /clientpacket command
  # Pathfinders
  quantumpen.pathfinder:
    default: op
    description: Access to all Pathfinder Options
    children:
      quantumpen.pathfinder.add: true
      quantumpen.pathfinder.remove: true
      quantumpen.pathfinder.clear: true
      quantumpen.pathfinder.list: true
      quantumpen.pathfinder.controller: true
  quantumpen.pathfinders.controller:
    default: op
    description: Enable ability to use entity controllers  
  quantumpen.pathfinder.add:
    default: op
    description: Enable ability to add pathfinders
  quantumpen.pathfinder.list:
    default: op
    description: Enable ability to list pathfinders
  quantumpen.pathfinder.remove:
    default: op
    description: Enable ability to remove pathfinders
  quantumpen.pathfinder.clear:
    default: op
    description: Enable ability to clear pathfinders
  # World & Server
  quantumpen.world:
    default: op
    description: Enable ability to edit world data
    children:
      quantumpen.world.chunk: true
      quantumpen.world.block: true
      quantumpen.world.create: true
      quantumpen.world.unload: true
  quantumpen.world.chunk:
    default: op
    description: Enable ability to edit chunk data
  quantumpen.server:
    default: op
    description: Enable ability to edit & fetch server data
    children:
      quantumpen.server.playerdata: true
  quantumpen.server.playerdata:
    default: op
    description: Enable ability to fetch player data
  quantumpen.world.block:
    default: op
    description: Enable ability to edit & fetch block data
  quantumpen.world.create:
    default: op
    description: Enable ability to create worlds
      
  